config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :email, :phone, :smoker, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :show, :destroy]
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path, notice: 'Cliente cadastrado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @customer.update!(customer_params)
      redirect_to customer_path(@customer.id), notice: 'Cliente atualizado com sucesso!'
    else
      render :new
    end
  end

  def show; end

  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: 'Cliente apagado com sucesso!'
    else
      render customers_path
    end
  end

  private

  def customer_params
    params.require(:customer)
          .permit(:id, :name, :email, :phone, :smoker, :avatar)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>

  <%= f.label :email %>
  <%= f.text_field :email %> <br/>

  <%= f.label :phone %>
  <%= f.text_field :phone %> <br/>

  <%= f.label :smoker %>
  <%= f.select :smoker, [["Sim", 'Sim'], ["Não", 'Não']] %> <br/>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %> <br/>

  <%= f.submit action_name == 'new' ? 'Criar Cliente' : 'Atualizar Cliente' %>
<% end %>

app/views/customers/edit.html.erb
<h1> Editando Cliente </h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
  <p> <%= flash[:notice] %> </p>
<% end %>

<h1> Listando Clientes </h1>
<table>
  <thead>
  <th>Nome</th>
  <th>Email</th>
  <th>Telefone</th>
  <th>Fumante?</th>
  <th>Visualizar</th>
  <th>Editar</th>
  <th>Excluir</th>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td>
        <%= customer.name %>
      </td>
      <td>
        <%= customer.email %>
      </td>
      <td>
        <%= customer.phone %>
      </td>
      <td>
        <%= customer.smoker %>
      </td>
      <td>
        <%= link_to 'Visualizar', customer_path(customer.id) %>
      </td>
      <td>
        <%= link_to 'Editar', edit_customer_path(customer.id) %>
      </td>
      <td>
        <%= link_to 'Excluir', customer_path(customer.id),
                    method: :delete, data: { confirm: 'Tem certeza?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Novo Cliente', new_customer_path %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <% @customer.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
<% end %>

<h1> Novo Cliente </h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
  <p> <%= flash[:notice] %> </p>
<% end %>

<h1>Mostrando Cliente</h1>

<p>
  <strong>Nome</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Telefone</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Avatar</strong>
  <%= @customer.avatar %>
</p>

<p>
  <strong>Fumante?</strong>
  <%= @customer.smoker %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<html>
  <h1>Seja Bem-Vindo</h1>
  <ul>
    <li>
      <%= link_to "Cadastro de Clientes", customers_path %>
    </li>
  </ul>
</html>